server {
    listen 80;
    server_name prisme.axelhoffmann.fr;

    root /usr/share/nginx/html;
    index index.html;

    # Pages de partage — accès public sans authentification
    location /share/ {
        auth_basic off;
        try_files $uri /share.html;
    }

    # Tout le reste — accès restreint
    location / {
        auth_basic "Prisme — Accès restreint";
        auth_basic_user_file /etc/nginx/.htpasswd;
        try_files $uri $uri/ /index.html;
    }
}
