server {
    listen 80;
    server_name prisme.axelhoffmann.fr;

    root /usr/share/nginx/html;
    index index.html;

    # Tout public — l'auth est gérée côté JS dans le dashboard
    location / {
        try_files $uri $uri/ /index.html;
    }
}
