-- Table référentiel géographique pour l'autocomplétion
CREATE TABLE IF NOT EXISTS geo_places (
    id          SERIAL      PRIMARY KEY,
    name        TEXT        NOT NULL,
    type        TEXT        NOT NULL, -- region, departement, intercommunalite, commune
    dept_name   TEXT,
    region_name TEXT,
    population  INTEGER,
    keywords    TEXT[]      NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_geo_places_name ON geo_places USING gin(to_tsvector('french', name));
CREATE INDEX IF NOT EXISTS idx_geo_places_type ON geo_places(type);

TRUNCATE geo_places RESTART IDENTITY;

INSERT INTO geo_places (name, type, region_name, dept_name, population, keywords) VALUES
-- RÉGIONS
('Île-de-France','region',NULL,NULL,12278210,ARRAY['île-de-france','idf','paris','seine']),
('Hauts-de-France','region',NULL,NULL,6004526,ARRAY['hauts-de-france','nord','pas-de-calais','lille','amiens']),
('Grand Est','region',NULL,NULL,5569187,ARRAY['grand-est','alsace','lorraine','champagne','strasbourg','nancy','reims','metz']),
('Normandie','region',NULL,NULL,3303500,ARRAY['normandie','rouen','caen','le havre']),
('Bretagne','region',NULL,NULL,3385478,ARRAY['bretagne','rennes','brest','quimper']),
('Pays de la Loire','region',NULL,NULL,3801797,ARRAY['pays-de-la-loire','nantes','angers','le mans']),
('Centre-Val de Loire','region',NULL,NULL,2572853,ARRAY['centre-val-de-loire','orléans','tours','bourges']),
('Bourgogne-Franche-Comté','region',NULL,NULL,2807534,ARRAY['bourgogne','franche-comté','dijon','besançon']),
('Auvergne-Rhône-Alpes','region',NULL,NULL,8097822,ARRAY['auvergne','rhône-alpes','lyon','grenoble','clermont-ferrand','saint-étienne']),
('Nouvelle-Aquitaine','region',NULL,NULL,6088763,ARRAY['nouvelle-aquitaine','bordeaux','limoges','poitiers']),
('Occitanie','region',NULL,NULL,5973059,ARRAY['occitanie','toulouse','montpellier','nîmes']),
('Provence-Alpes-Côte d''Azur','region',NULL,NULL,5081156,ARRAY['provence','alpes','côte-d''azur','marseille','nice','toulon']),
('Corse','region',NULL,NULL,340440,ARRAY['corse','ajaccio','bastia']),

-- DÉPARTEMENTS
('Ain','departement','Auvergne-Rhône-Alpes',NULL,643350,ARRAY['ain','bourg-en-bresse','01']),
('Aisne','departement','Hauts-de-France',NULL,527455,ARRAY['aisne','laon','saint-quentin','02']),
('Allier','departement','Auvergne-Rhône-Alpes',NULL,337988,ARRAY['allier','moulins','vichy','03']),
('Alpes-de-Haute-Provence','departement','Provence-Alpes-Côte d''Azur',NULL,165197,ARRAY['alpes-de-haute-provence','digne','04']),
('Hautes-Alpes','departement','Provence-Alpes-Côte d''Azur',NULL,141284,ARRAY['hautes-alpes','gap','05']),
('Alpes-Maritimes','departement','Provence-Alpes-Côte d''Azur',NULL,1094040,ARRAY['alpes-maritimes','nice','cannes','antibes','06']),
('Ardèche','departement','Auvergne-Rhône-Alpes',NULL,328808,ARRAY['ardèche','privas','aubenas','07']),
('Ardennes','departement','Grand Est',NULL,272478,ARRAY['ardennes','charleville-mézières','08']),
('Ariège','departement','Occitanie',NULL,153406,ARRAY['ariège','foix','09']),
('Aube','departement','Grand Est',NULL,309128,ARRAY['aube','troyes','10']),
('Aude','departement','Occitanie',NULL,376847,ARRAY['aude','carcassonne','narbonne','11']),
('Aveyron','departement','Occitanie',NULL,279594,ARRAY['aveyron','rodez','millau','12']),
('Bouches-du-Rhône','departement','Provence-Alpes-Côte d''Azur',NULL,2059795,ARRAY['bouches-du-rhône','marseille','aix-en-provence','arles','13']),
('Calvados','departement','Normandie',NULL,691774,ARRAY['calvados','caen','bayeux','lisieux','14']),
('Cantal','departement','Auvergne-Rhône-Alpes',NULL,144692,ARRAY['cantal','aurillac','15']),
('Charente','departement','Nouvelle-Aquitaine',NULL,352705,ARRAY['charente','angoulême','16']),
('Charente-Maritime','departement','Nouvelle-Aquitaine',NULL,651310,ARRAY['charente-maritime','la rochelle','rochefort','saintes','17']),
('Cher','departement','Centre-Val de Loire',NULL,302304,ARRAY['cher','bourges','18']),
('Corrèze','departement','Nouvelle-Aquitaine',NULL,241606,ARRAY['corrèze','tulle','brive','19']),
('Côte-d''Or','departement','Bourgogne-Franche-Comté',NULL,535478,ARRAY['côte-d''or','dijon','beaune','21']),
('Côtes-d''Armor','departement','Bretagne',NULL,601001,ARRAY['côtes-d''armor','saint-brieuc','22']),
('Creuse','departement','Nouvelle-Aquitaine',NULL,112922,ARRAY['creuse','guéret','23']),
('Dordogne','departement','Nouvelle-Aquitaine',NULL,415496,ARRAY['dordogne','périgueux','bergerac','24']),
('Doubs','departement','Bourgogne-Franche-Comté',NULL,543788,ARRAY['doubs','besançon','montbéliard','25']),
('Drôme','departement','Auvergne-Rhône-Alpes',NULL,527461,ARRAY['drôme','valence','romans','26']),
('Eure','departement','Normandie',NULL,594219,ARRAY['eure','évreux','vernon','27']),
('Eure-et-Loir','departement','Centre-Val de Loire',NULL,433394,ARRAY['eure-et-loir','chartres','dreux','28']),
('Finistère','departement','Bretagne',NULL,911026,ARRAY['finistère','brest','quimper','lorient','29']),
('Gard','departement','Occitanie',NULL,748437,ARRAY['gard','nîmes','alès','30']),
('Haute-Garonne','departement','Occitanie',NULL,1399762,ARRAY['haute-garonne','toulouse','colomiers','31']),
('Gers','departement','Occitanie',NULL,191428,ARRAY['gers','auch','32']),
('Gironde','departement','Nouvelle-Aquitaine',NULL,1625783,ARRAY['gironde','bordeaux','mérignac','33']),
('Hérault','departement','Occitanie',NULL,1175623,ARRAY['hérault','montpellier','sète','béziers','34']),
('Ille-et-Vilaine','departement','Bretagne',NULL,1083083,ARRAY['ille-et-vilaine','rennes','saint-malo','35']),
('Indre','departement','Centre-Val de Loire',NULL,220258,ARRAY['indre','châteauroux','36']),
('Indre-et-Loire','departement','Centre-Val de Loire',NULL,606511,ARRAY['indre-et-loire','tours','37']),
('Isère','departement','Auvergne-Rhône-Alpes',NULL,1270870,ARRAY['isère','grenoble','vienne','38']),
('Jura','departement','Bourgogne-Franche-Comté',NULL,259743,ARRAY['jura','lons-le-saunier','39']),
('Landes','departement','Nouvelle-Aquitaine',NULL,415543,ARRAY['landes','mont-de-marsan','dax','40']),
('Loir-et-Cher','departement','Centre-Val de Loire',NULL,333037,ARRAY['loir-et-cher','blois','vendôme','41']),
('Loire','departement','Auvergne-Rhône-Alpes',NULL,764071,ARRAY['loire','saint-étienne','roanne','42']),
('Haute-Loire','departement','Auvergne-Rhône-Alpes',NULL,228530,ARRAY['haute-loire','le puy-en-velay','43']),
('Loire-Atlantique','departement','Pays de la Loire',NULL,1429272,ARRAY['loire-atlantique','nantes','saint-nazaire','44']),
('Loiret','departement','Centre-Val de Loire',NULL,677758,ARRAY['loiret','orléans','45']),
('Lot','departement','Occitanie',NULL,174517,ARRAY['lot','cahors','figeac','46']),
('Lot-et-Garonne','departement','Nouvelle-Aquitaine',NULL,333578,ARRAY['lot-et-garonne','agen','47']),
('Lozère','departement','Occitanie',NULL,76050,ARRAY['lozère','mende','48']),
('Maine-et-Loire','departement','Pays de la Loire',NULL,813557,ARRAY['maine-et-loire','angers','saumur','cholet','49']),
('Manche','departement','Normandie',NULL,495285,ARRAY['manche','cherbourg','saint-lô','50']),
('Marne','departement','Grand Est',NULL,570978,ARRAY['marne','reims','châlons-en-champagne','51']),
('Haute-Marne','departement','Grand Est',NULL,172655,ARRAY['haute-marne','chaumont','52']),
('Mayenne','departement','Pays de la Loire',NULL,306264,ARRAY['mayenne','laval','53']),
('Meurthe-et-Moselle','departement','Grand Est',NULL,733194,ARRAY['meurthe-et-moselle','nancy','longwy','54']),
('Meuse','departement','Grand Est',NULL,185203,ARRAY['meuse','bar-le-duc','verdun','55']),
('Morbihan','departement','Bretagne',NULL,756063,ARRAY['morbihan','vannes','lorient','56']),
('Moselle','departement','Grand Est',NULL,1043131,ARRAY['moselle','metz','thionville','57']),
('Nièvre','departement','Bourgogne-Franche-Comté',NULL,204848,ARRAY['nièvre','nevers','58']),
('Nord','departement','Hauts-de-France',NULL,2604361,ARRAY['nord','lille','roubaix','tourcoing','valenciennes','59']),
('Oise','departement','Hauts-de-France',NULL,830337,ARRAY['oise','beauvais','compiègne','60']),
('Orne','departement','Normandie',NULL,279000,ARRAY['orne','alençon','flers','61']),
('Pas-de-Calais','departement','Hauts-de-France',NULL,1475681,ARRAY['pas-de-calais','calais','boulogne','lens','arras','62']),
('Puy-de-Dôme','departement','Auvergne-Rhône-Alpes',NULL,663050,ARRAY['puy-de-dôme','clermont-ferrand','thiers','63']),
('Pyrénées-Atlantiques','departement','Nouvelle-Aquitaine',NULL,683038,ARRAY['pyrénées-atlantiques','pau','bayonne','64']),
('Hautes-Pyrénées','departement','Occitanie',NULL,226143,ARRAY['hautes-pyrénées','tarbes','lourdes','65']),
('Pyrénées-Orientales','departement','Occitanie',NULL,479979,ARRAY['pyrénées-orientales','perpignan','66']),
('Bas-Rhin','departement','Grand Est',NULL,1140925,ARRAY['bas-rhin','strasbourg','haguenau','67']),
('Haut-Rhin','departement','Grand Est',NULL,763744,ARRAY['haut-rhin','mulhouse','colmar','68']),
('Rhône','departement','Auvergne-Rhône-Alpes',NULL,1882588,ARRAY['rhône','lyon','villeurbanne','69']),
('Haute-Saône','departement','Bourgogne-Franche-Comté',NULL,240680,ARRAY['haute-saône','vesoul','70']),
('Saône-et-Loire','departement','Bourgogne-Franche-Comté',NULL,550044,ARRAY['saône-et-loire','mâcon','chalon-sur-saône','71']),
('Sarthe','departement','Pays de la Loire',NULL,564620,ARRAY['sarthe','le mans','72']),
('Savoie','departement','Auvergne-Rhône-Alpes',NULL,438775,ARRAY['savoie','chambéry','albertville','73']),
('Haute-Savoie','departement','Auvergne-Rhône-Alpes',NULL,820258,ARRAY['haute-savoie','annecy','thonon','74']),
('Paris','departement','Île-de-France',NULL,2148271,ARRAY['paris','75']),
('Seine-Maritime','departement','Normandie',NULL,1275952,ARRAY['seine-maritime','rouen','le havre','dieppe','76']),
('Seine-et-Marne','departement','Île-de-France',NULL,1418218,ARRAY['seine-et-marne','melun','meaux','77']),
('Yvelines','departement','Île-de-France',NULL,1454466,ARRAY['yvelines','versailles','saint-germain','78']),
('Deux-Sèvres','departement','Nouvelle-Aquitaine',NULL,370970,ARRAY['deux-sèvres','niort','79']),
('Somme','departement','Hauts-de-France',NULL,572443,ARRAY['somme','amiens','abbeville','80']),
('Tarn','departement','Occitanie',NULL,390158,ARRAY['tarn','albi','castres','81']),
('Tarn-et-Garonne','departement','Occitanie',NULL,261028,ARRAY['tarn-et-garonne','montauban','82']),
('Var','departement','Provence-Alpes-Côte d''Azur',NULL,1082979,ARRAY['var','toulon','draguignan','fréjus','83']),
('Vaucluse','departement','Provence-Alpes-Côte d''Azur',NULL,565085,ARRAY['vaucluse','avignon','carpentras','84']),
('Vendée','departement','Pays de la Loire',NULL,685659,ARRAY['vendée','la roche-sur-yon','85']),
('Vienne','departement','Nouvelle-Aquitaine',NULL,437869,ARRAY['vienne','poitiers','86']),
('Haute-Vienne','departement','Nouvelle-Aquitaine',NULL,368994,ARRAY['haute-vienne','limoges','87']),
('Vosges','departement','Grand Est',NULL,361685,ARRAY['vosges','épinal','88']),
('Yonne','departement','Bourgogne-Franche-Comté',NULL,338291,ARRAY['yonne','auxerre','sens','89']),
('Territoire de Belfort','departement','Bourgogne-Franche-Comté',NULL,142467,ARRAY['territoire-de-belfort','belfort','90']),
('Essonne','departement','Île-de-France',NULL,1296130,ARRAY['essonne','évry','corbeil','91']),
('Hauts-de-Seine','departement','Île-de-France',NULL,1624357,ARRAY['hauts-de-seine','nanterre','boulogne-billancourt','neuilly','92']),
('Seine-Saint-Denis','departement','Île-de-France',NULL,1657398,ARRAY['seine-saint-denis','saint-denis','montreuil','bobigny','93']),
('Val-de-Marne','departement','Île-de-France',NULL,1387926,ARRAY['val-de-marne','créteil','vincennes','94']),
('Val-d''Oise','departement','Île-de-France',NULL,1228618,ARRAY['val-d''oise','cergy','pontoise','95']),

-- PRINCIPALES INTERCOMMUNALITÉS
('Métropole du Grand Paris','intercommunalite','Île-de-France',NULL,7209261,ARRAY['grand paris','métropole grand paris','mgp']),
('Métropole de Lyon','intercommunalite','Auvergne-Rhône-Alpes',NULL,1412046,ARRAY['métropole de lyon','grand lyon','métropole lyonnaise']),
('Métropole Aix-Marseille-Provence','intercommunalite','Provence-Alpes-Côte d''Azur',NULL,1898997,ARRAY['aix-marseille','métropole aix-marseille','amp']),
('Métropole Européenne de Lille','intercommunalite','Hauts-de-France',NULL,1163995,ARRAY['métropole européenne de lille','mel','lille métropole']),
('Bordeaux Métropole','intercommunalite','Nouvelle-Aquitaine',NULL,826775,ARRAY['bordeaux métropole','cub','gironde métropole']),
('Toulouse Métropole','intercommunalite','Occitanie',NULL,783438,ARRAY['toulouse métropole','sipfn']),
('Nantes Métropole','intercommunalite','Pays de la Loire',NULL,657805,ARRAY['nantes métropole']),
('Rennes Métropole','intercommunalite','Bretagne',NULL,459494,ARRAY['rennes métropole']),
('Strasbourg Eurométropole','intercommunalite','Grand Est',NULL,506800,ARRAY['strasbourg','eurométropole','eurométropole de strasbourg']),
('Grenoble-Alpes Métropole','intercommunalite','Auvergne-Rhône-Alpes',NULL,454047,ARRAY['grenoble alpes métropole','métro grenoble']),
('Montpellier Méditerranée Métropole','intercommunalite','Occitanie',NULL,462231,ARRAY['montpellier méditerranée','montpellier métropole']),
('Nice Côte d''Azur','intercommunalite','Provence-Alpes-Côte d''Azur',NULL,550457,ARRAY['nice côte d''azur','nca','métropole nice']),
('Toulon Provence Méditerranée','intercommunalite','Provence-Alpes-Côte d''Azur',NULL,451600,ARRAY['toulon provence méditerranée','tpm']),
('Rouen Normandie Métropole','intercommunalite','Normandie',NULL,497600,ARRAY['rouen métropole','métropole rouen normandie','mrn']),
('Clermont Auvergne Métropole','intercommunalite','Auvergne-Rhône-Alpes',NULL,296826,ARRAY['clermont auvergne métropole','cam','clermont métropole']),
('Saint-Étienne Métropole','intercommunalite','Auvergne-Rhône-Alpes',NULL,407780,ARRAY['saint-étienne métropole','sem']),
('Dijon Métropole','intercommunalite','Bourgogne-Franche-Comté',NULL,262523,ARRAY['dijon métropole']),
('Brest Métropole','intercommunalite','Bretagne',NULL,218838,ARRAY['brest métropole','bmo']),
('Grand Besançon Métropole','intercommunalite','Bourgogne-Franche-Comté',NULL,199635,ARRAY['grand besançon métropole','gbm']),
('Tours Métropole Val de Loire','intercommunalite','Centre-Val de Loire',NULL,357046,ARRAY['tours métropole','tmvl']),
('Orléans Métropole','intercommunalite','Centre-Val de Loire',NULL,288612,ARRAY['orléans métropole']),
('Angers Loire Métropole','intercommunalite','Pays de la Loire',NULL,298798,ARRAY['angers loire métropole','alm']),
('Le Mans Métropole','intercommunalite','Pays de la Loire',NULL,213960,ARRAY['le mans métropole']),
('Metz Métropole','intercommunalite','Grand Est',NULL,228131,ARRAY['metz métropole']),
('Nancy Grand Cœur','intercommunalite','Grand Est',NULL,261220,ARRAY['nancy grand cœur','grand nancy']),
('Caen la Mer','intercommunalite','Normandie',NULL,245143,ARRAY['caen la mer','caen métropole']),
('Perpignan Méditerranée','intercommunalite','Occitanie',NULL,271540,ARRAY['perpignan méditerranée','pmca']),

-- PRINCIPALES COMMUNES
('Paris','commune','Île-de-France','Paris',2148271,ARRAY['paris','ville de paris']),
('Marseille','commune','Provence-Alpes-Côte d''Azur','Bouches-du-Rhône',868277,ARRAY['marseille','phocéenne']),
('Lyon','commune','Auvergne-Rhône-Alpes','Rhône',522228,ARRAY['lyon','lyonnais']),
('Toulouse','commune','Occitanie','Haute-Garonne',486828,ARRAY['toulouse','ville rose']),
('Nice','commune','Provence-Alpes-Côte d''Azur','Alpes-Maritimes',340017,ARRAY['nice','niçois']),
('Nantes','commune','Pays de la Loire','Loire-Atlantique',320732,ARRAY['nantes','nantais']),
('Montpellier','commune','Occitanie','Hérault',295542,ARRAY['montpellier','montpelliérain']),
('Strasbourg','commune','Grand Est','Bas-Rhin',284677,ARRAY['strasbourg','strasbourgeois']),
('Bordeaux','commune','Nouvelle-Aquitaine','Gironde',257804,ARRAY['bordeaux','bordelais']),
('Lille','commune','Hauts-de-France','Nord',232741,ARRAY['lille','lillois']),
('Rennes','commune','Bretagne','Ille-et-Vilaine',220488,ARRAY['rennes','rennais']),
('Reims','commune','Grand Est','Marne',183042,ARRAY['reims','rémois']),
('Le Havre','commune','Normandie','Seine-Maritime',172074,ARRAY['le havre','havrais']),
('Saint-Étienne','commune','Auvergne-Rhône-Alpes','Loire',170543,ARRAY['saint-étienne','stéphanois']),
('Toulon','commune','Provence-Alpes-Côte d''Azur','Var',170170,ARRAY['toulon','toulonnais']),
('Grenoble','commune','Auvergne-Rhône-Alpes','Isère',158198,ARRAY['grenoble','grenoblois']),
('Dijon','commune','Bourgogne-Franche-Comté','Côte-d''Or',155090,ARRAY['dijon','dijonnais']),
('Angers','commune','Pays de la Loire','Maine-et-Loire',154508,ARRAY['angers','angevin']),
('Villeurbanne','commune','Auvergne-Rhône-Alpes','Rhône',150646,ARRAY['villeurbanne']),
('Nîmes','commune','Occitanie','Gard',150564,ARRAY['nîmes','nîmois']),
('Aix-en-Provence','commune','Provence-Alpes-Côte d''Azur','Bouches-du-Rhône',142469,ARRAY['aix-en-provence','aixois']),
('Clermont-Ferrand','commune','Auvergne-Rhône-Alpes','Puy-de-Dôme',140957,ARRAY['clermont-ferrand','clermontois']),
('Le Mans','commune','Pays de la Loire','Sarthe',143599,ARRAY['le mans','manceau']),
('Brest','commune','Bretagne','Finistère',140064,ARRAY['brest','brestois']),
('Amiens','commune','Hauts-de-France','Somme',134393,ARRAY['amiens','amiénois']),
('Tours','commune','Centre-Val de Loire','Indre-et-Loire',136463,ARRAY['tours','tourangeau']),
('Limoges','commune','Nouvelle-Aquitaine','Haute-Vienne',131834,ARRAY['limoges','limougeaud']),
('Metz','commune','Grand Est','Moselle',116429,ARRAY['metz','messin']),
('Perpignan','commune','Occitanie','Pyrénées-Orientales',122158,ARRAY['perpignan','perpignanais']),
('Besançon','commune','Bourgogne-Franche-Comté','Doubs',116952,ARRAY['besançon','bisontin']),
('Orléans','commune','Centre-Val de Loire','Loiret',114644,ARRAY['orléans','orléanais']),
('Rouen','commune','Normandie','Seine-Maritime',110145,ARRAY['rouen','rouennais']),
('Mulhouse','commune','Grand Est','Haut-Rhin',110359,ARRAY['mulhouse','mulhousien']),
('Caen','commune','Normandie','Calvados',105354,ARRAY['caen','caennais']),
('Nancy','commune','Grand Est','Meurthe-et-Moselle',103552,ARRAY['nancy','nancéien']),
('Saint-Denis','commune','Île-de-France','Seine-Saint-Denis',111106,ARRAY['saint-denis']),
('Argenteuil','commune','Île-de-France','Val-d''Oise',111015,ARRAY['argenteuil']),
('Montreuil','commune','Île-de-France','Seine-Saint-Denis',107530,ARRAY['montreuil']),
('Roubaix','commune','Hauts-de-France','Nord',97706,ARRAY['roubaix','roubaisien']),
('Dunkerque','commune','Hauts-de-France','Nord',86785,ARRAY['dunkerque','dunkerquois']),
('Avignon','commune','Provence-Alpes-Côte d''Azur','Vaucluse',93751,ARRAY['avignon','avignonnais']),
('Pau','commune','Nouvelle-Aquitaine','Pyrénées-Atlantiques',77489,ARRAY['pau','palois']),
('Poitiers','commune','Nouvelle-Aquitaine','Vienne',88291,ARRAY['poitiers','poitevin']),
('La Rochelle','commune','Nouvelle-Aquitaine','Charente-Maritime',79630,ARRAY['la rochelle','rochelais']),
('Cannes','commune','Provence-Alpes-Côte d''Azur','Alpes-Maritimes',73854,ARRAY['cannes','cannois']),
('Antibes','commune','Provence-Alpes-Côte d''Azur','Alpes-Maritimes',75828,ARRAY['antibes']),
('Quimper','commune','Bretagne','Finistère',64141,ARRAY['quimper','quimpérois']),
('Lorient','commune','Bretagne','Morbihan',57821,ARRAY['lorient','lorientais']),
('Bayonne','commune','Nouvelle-Aquitaine','Pyrénées-Atlantiques',52079,ARRAY['bayonne','bayonnais']),
('Colmar','commune','Grand Est','Haut-Rhin',70785,ARRAY['colmar','colmarien']),
('Troyes','commune','Grand Est','Aube',61327,ARRAY['troyes','troyen']),
('Chartres','commune','Centre-Val de Loire','Eure-et-Loir',39138,ARRAY['chartres','chartrain']),
('Bourges','commune','Centre-Val de Loire','Cher',66011,ARRAY['bourges','berruyer']),
('Valence','commune','Auvergne-Rhône-Alpes','Drôme',63715,ARRAY['valence','valentinois']),
('Chambéry','commune','Auvergne-Rhône-Alpes','Savoie',60349,ARRAY['chambéry','chambérien']),
('Annecy','commune','Auvergne-Rhône-Alpes','Haute-Savoie',135501,ARRAY['annecy','annécien']),
('Bordeaux','commune','Nouvelle-Aquitaine','Gironde',257804,ARRAY['bordeaux','bordelais'])
ON CONFLICT DO NOTHING;
